version: "3.9"
services:
  pygwalker-workspace:
    container_name: pygwalker-workspace
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    tty: true
    ports:
      - "8501:8501"
    volumes:
      - ./db:/workspace/db
