version: "3.9"
services:
  pygwalker-workspace-dev:
    container_name: pygwalker-workspace-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - ../:/workspace
